### ISSUE TITLE
misunderstood of -v option in kourou instance:spawn -v

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kourou#59]
The `-v` option of `kourou instance:spawn` only allow to choose between both 1 and 2 Kuzzle `major` version .
It should be named like `kuzzleVersion` or `majorVersion` or allow user to specify a full version like `2.3.3`

**Comment by Aschen** [comment]
I don't understand this issue, the `-v` flag prints Kourou version and then exit
```
➜  ~ kourou -v                                
kourou/0.13.1 linux-x64 node-v12.16.3
```

**Comment by berthieresteban** [comment]
@Aschen `kourou instance:spawn -v` I'll rename the issue

**Comment by alexandrebouthinon** [comment]
Instance module will be removed
