### ISSUE TITLE
Add es:snapshot module

### ISSUE THREAD

**Issue by rolljee** [kuzzleio/kourou#70]
- [ ] `es:snapshot:dump <es-host> <repo_name> <snapshot_name>`
* Dump the ES data into a snapshot

- [ ] `es:snapshot:restore <es-host> <repo_name> <snapshot_name>`
* Restore a specific snapshot from a specific repository to an ES

- [ ] `es:snapshot:create-repository <es-host> <repo_name> <path_of_the_repo> --compress`
* Create a repository into an ES cluster

- [ ]  `es:snapshot:list-repository <es-host>`
* List repository known by the current ES

- [ ] `es:snapshot:list-snapshot <es-host> <repo_name>`
* List snapshot from a repository known by the current ES

<details><summary>Original issue</summary>
- [ ] `es:snapshot:dump --host=<es-host> --repository=<repo_name> --name=<snapshot_name>`
* Dump the ES data into a snapshot

- [ ] `es:snapshot:restore --host=<es-host> --repository=<repo_name> --snapshot=<snapshot_name>`
* Restore a specific snapshot from a specific repository to an ES

- [ ] `es:snapshot:create_repository --host=<es-host> --repository=<repo_name> --location=<path_of_the_repo> --compress=<true|false>`
* Create a repository into an ES cluster

- [ ]  `es:snapshot:list_repository --host=<es-host>`
* List repository known by the current ES

- [ ] `es:snapshot:list_snapshot --host=<es-host> --repository=<repo_name>`
* List snapshot from a repository known by the current ES
</details>

**Comment by Aschen** [comment]
Elasticsearch host should be configurable through an environment variable IMHO

**Comment by rolljee** [comment]
Seem's like github does not close this automatically :x
