### ISSUE TITLE
nodemon not installed in devDeps inside templates file

### ISSUE THREAD

**Issue by rolljee** [kuzzleio/kourou#79]
app:scaffold command use nodemon to watch for changes.

But nodemon is not part of devDeps inside the [package.json](https://github.com/kuzzleio/kourou/blob/develop/templates/app-scaffold/ts/package.json)

**Comment by Aschen** [comment]
`app:scaffold` will not use nodemon directly anymore after https://github.com/kuzzleio/kourou/pull/78 but rather use a Docker container

**Comment by rolljee** [comment]
Alright, I think it might be a good idea to keep it in devDeps for user that don't directly use the docker image wdyt ?
Feel free to close it if u think it's not needed

docker image also sounds good to me

**Comment by scottinet** [comment]
Don't use nodemon for the dev stack, use our own reloader instead (`docker/scripts/reloader.js`)

**Comment by Aschen** [comment]
@rolljee I'm not fond of adding `nodemon` as dev dependency for Kourou since the CLI is mainly used during development process and I don't want to make people download nodemon if they don't need it

**Comment by rolljee** [comment]
Closing then
