### ISSUE TITLE
New command kourou app:doctor

### ISSUE THREAD

**Issue by alexandrebouthinon** [kuzzleio/kourou#85]
In the same way Flutter provide the super convenient `flutter doctor` command to perform checks before development begin (Android SDK version, Android emulator version, Dart version...), we decided that we needed our own command.

Checks and information retrieved need to be discuss but IMO we need at least:
* Node.js:
    * Installed and configured (binary file in `$PATH` for example)
    * Version
* Kuzzle version check
* Elasticsearch:
    * Running
    * Version
    * Kernel settings (`vm.max_map_count=262144`)
* Redis:
    * Running
    * Version

Let's talk about it below 😄

**Comment by xbill82** [comment]
And the kernel memory settings needed by Elastic

**Comment by alexandrebouthinon** [comment]
Yes, I add it to the list

**Comment by Aschen** [comment]
> And the kernel memory settings needed by Elastic

This is don't need anymore with ES 7

**Comment by alexandrebouthinon** [comment]
@Aschen According to the Elasticsearch 7.x documentation https://www.elastic.co/guide/en/elasticsearch/reference/7.x/vm-max-map-count.html

**Comment by Aschen** [comment]
I have 65530 and I never had any trouble but when I'm running Kuzzle v1 with ES 5 then I have to increase it
```
$ cat /proc/sys/vm/max_map_count                                         
65530
```

**Comment by OlivierCavadenti** [comment]
Can be useful:

- Ping Redis and ElasticSearch urls (default urls or custom urls)
- Check lib installs (os dependant): 
      bash-completion \
      build-essential \
      curl \
      g++ \
      gdb \
      git \
      gnupg \
      libfontconfig \
      libzmq3-dev \
      python3 \
      procps \
      wget \
      libunwind-dev
- Node version check (build and kuzzle node version) with mismatch check
- check docker compose install
- check if an admin exists
