### ISSUE TITLE
app:scaffold stuck on dependencies install

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kourou#91]
On Mac, `app:scaffold` is stuck on `Installing dependencies (this can take some time)` forever...

... Or maybe it's just soooooooo long we need some feedback in the stdout to be reassured it's not stuck.

**Comment by Aschen** [comment]
Hmm maybe it's really stuck.. 
I tried to display only one line of the subcommand stdout but I didn't succeed (but didn't tried too much also :sweat_smile: )
